#!/usr/bin/env bash

logfile="${HOME}/${0}.log"

function checksudo {
	if [[ $(id --user) == 0 ]]
	then
		echo 'You are running as root. Run this as your normal user; the script will prompt for a password only when necessary.'
		exit 1
	fi
}

function preplogs {
	sudo rm --force $logfile
}

function install {
	stepname='installing git'
	packages='git'
	vbox_guest='virtualbox-guest-dkms'
	
	echo "----------begin ${stepname}----------" | tee --append $logfile

	sudo apt-get update --assume-yes &>> $logfile || earlyexit "${stepname}: update"
	sudo apt-get install $packages --assume-yes &>> $logfile || earlyexit "${stepname}: install ${packages}"
	sudo apt-get autoremove --assume-yes &>> $logfile || earlyexit "${stepname}: autoremove"
	sudo apt-get autoclean --assume-yes &>> $logfile || earlyexit "${stepname}: autoclean"

	checklog || earlyexit "${stepname}"
	
	echo "----------${stepname} succeeded----------" | tee --append $logfile
}

function customize {
	git config --global core.editor vim
	git config --global push.default simple
	git config --global alias.pu push
	git config --global alias.st status
	git config --global alias.co commit
	git config --global alias.ad add
}

function checklog {
	#necessary because apt-get may emit a problem to stdout or stderr but still return 0
	problem_count=$(grep --count --extended-regexp '(Err )|(W: )|(E: )' $logfile)
	
	if [[ $problem_count != 0 ]]
	then
		return 1
	else
		return 0
	fi
}

function earlyexit {
	echo "----------a problem occurred during ${1}----------" | tee --append $logfile
	exit 1
}

checksudo
preplogs
install

exit 0

