#!/usr/bin/env bash

logfile="${HOME}/${0}.log"

function checksudo {
	if [[ $(id --user) == 0 ]]
	then
		echo 'You are running as root. Run this as your normal user; the script will prompt for a password only when necessary.'
		exit 1
	fi
}

function preplogs {
	sudo rm --force $logfile
}

function preinstall {
	stepname='pre-installation package maintenance'
	echo "----------begin ${stepname}----------" | tee --append $logfile
	
	sudo apt-get autoremove --assume-yes &>> $logfile || earlyexit "${stepname}: autoremove"
	sudo apt-get autoclean --assume-yes &>> $logfile || earlyexit "${stepname}: autoclean"
	sudo apt-get update --assume-yes &>> $logfile || earlyexit "${stepname}: update"
	sudo apt-get upgrade --assume-yes &>> $logfile || earlyexit "${stepname}: upgrade"

	checklog || earlyexit "${stepname}"
	
	echo "----------${stepname} succeeded----------" | tee --append $logfile
}

function unneeded {
	stepname='removing unneeded packages'
	echo "----------begin ${stepname}----------" | tee --append $logfile

	removal_list='aisleriot brasero cheese deja-dup gnome-mahjongg gnome-sudoku gnomine libreoffice-calc libreoffice-gnome libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-presentation-minimizer libreoffice-style-human libreoffice-writer rhythmbox rhythmbox-plugin-magnatune shotwell simple-scan thunderbird thunderbird-gnome-support totem totem-mozilla unity-webapps-common'

	sudo apt-get remove $removal_list --assume-yes &>> $logfile || earlyexit "${stepname}: remove"

	checklog || earlyexit "${stepname}"
	
	echo "----------${stepname} succeeded----------" | tee --append $logfile
}

function keptback {
	stepname='installing kept-back packages'
	echo "----------begin ${stepname}----------" | tee --append $logfile
	
	kept_back_packages=$(sudo apt-get upgrade -s | sed -n '/back:/,/upgraded./p' | sed '1d;$d')
	
	sudo apt-get install $kept_back_packages --assume-yes &>> $logfile || earlyexit "${stepname}: install"

	checklog || earlyexit "${stepname}"
	
	echo "----------${stepname} succeeded----------" | tee --append $logfile
}

function install {
	stepname='installing custom packages'
	packages='git vim tree screen'
	
	echo "----------begin ${stepname}----------" | tee --append $logfile

	sudo apt-get install $packages --assume-yes &>> $logfile || earlyexit "${stepname}: install ${packages}"

	checklog || earlyexit "${stepname}"
	
	echo "----------${stepname} succeeded----------" | tee --append $logfile
}

function cleanup {
	stepname='post-installation package maintenance'
	echo "----------begin ${stepname}----------" | tee --append $logfile
	
	sudo apt-get autoremove --assume-yes &>> $logfile || earlyexit "${stepname}: autoremove"
	sudo apt-get autoclean --assume-yes &>> $logfile || earlyexit "${stepname}: autoclean"

	checklog || earlyexit "${stepname}"
	
	echo "----------${stepname} succeeded----------" | tee --append $logfile
}

function checklog {
	#necessary because apt-get may emit a problem to stdout or stderr but still return 0
	problem_count=$(grep --count --extended-regexp '(Err )|(W: )|(E: )' $logfile)
	
	if [[ $problem_count != 0 ]]
	then
		return 1
	else
		return 0
	fi
}

function earlyexit {
	echo "----------a problem occurred during ${1}----------" | tee --append $logfile
	exit 1
}


logfile='./bash-machine-setup/packages.log'
rm --force $logfile

checksudo
preplogs
preinstall
unneeded
keptback
install
cleanup

exit 0

