#!/usr/bin/env bash

if [[ $(id --user) == 0 ]]
then
	echo 'You are running as root. Run this as your normal user; the script will prompt for a password only when necessary.'
	exit 1
fi

#turn off online search results
gsettings set com.canonical.Unity.Lenses remote-content-search 'none'

#turn on firewall
sudo ufw enable

exit 0

