#!/usr/bin/env bash

if [[ $(id --user) == 0 ]]
then
	echo 'You are running as root. Re-run as your normal user.'
	exit 1
fi

#show user name in menu bar
gsettings set com.canonical.indicator.session show-real-name-on-panel 'true'

#turn off update popup
gsettings set com.ubuntu.update-notifier no-show-notifications 'true'

#show menus in title bar
gsettings set com.canonical.Unity integrated-menus 'true'

#set small icons in launcher
dconf write /org/compiz/profiles/unity/plugins/unityshell/icon-size 20

#add terminal to Unity launcher
unity_launcher_schema='com.canonical.Unity.Launcher'
favorites_key='favorites'
existing_unity_favorites=$(gsettings get $unity_launcher_schema $favorites_key)

terminal_launcher='gnome-terminal.desktop'
terminal_launcher_path='/usr/share/applications/'${terminal_launcher}

favorites_application_prefix='application://'
favorites_terminal_launcher=${favorites_application_prefix}${terminal_launcher}

if $([ -f ${terminal_launcher_path} ] && $(!(echo $existing_unity_favorites | grep $favorites_terminal_launcher --silent)))
then
	existing_applications=($(echo $existing_unity_favorites | tr -d '][ ' | tr ',' '\n' | grep $favorites_application_prefix))
	updated_applications=(${existing_applications[*]} "'"${favorites_terminal_launcher}"'")
	
	not_applications=($(echo $existing_unity_favorites | tr -d '][ ' | tr ',' '\n' | grep $favorites_application_prefix --invert-match))
	
	combined=(${updated_applications[*]} ${not_applications[*]})
	combined_text=$(IFS=, ;echo "[${combined[*]}]")
	
	gsettings set $unity_launcher_schema $favorites_key $combined_text
fi

exit 0

